works on macos now

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -1,9 +1,11 @@
 #!/usr/bin/env bash
+set -e
 
 #TODAY="$(date "+%F")"
 WORKING_DIR="$HOME/Projects/journal_publisher"
 OUTPUT_DIR="$WORKING_DIR/_site"
 LOCATION="$WTTR_LOCATION"
+FILE_NAME="$(today).md"
 
 pushd "$WORKING_DIR"
 
@@ -29,6 +31,17 @@ shift $((OPTIND - 1))
 source ./partials/header.sh
 source ./partials/footer.sh
 
+preflight() {
+    local prereqs=( "cowsay" "figlet" "lolcat" "aha" )
+    for req in "${prereqs[@]}"; do
+        if ! command -v "$req" > /dev/null 2>&1; then
+            echo "Requires $req to be installed."
+            exit 1
+        fi
+    done
+}
+preflight
+
 title() {
     printf '%s\n' "<h1>$*</h1>"
 }
@@ -38,7 +51,7 @@ flow() {
 }
 
 div() {
-    printf '%s\n' "<div>$*</div>"
+    printf '%s' "<div>$*</div>"
 }
 
 paragraph() {
@@ -94,6 +107,15 @@ _cowsay() {
     printf '%s' "</span>"
 }
 
+parse_date() {
+    case "$OSTYPE" in
+        darwin*) date -j -f "%Y-%m-%d" "$1" +"%a, %d %b %Y" ;;
+        linux*)  date -d "$1" +"%a, %d %b %Y" ;;
+        msys*)   echo "Windows?"; exit 1 ;;
+        *)       echo "Cannot parse dates"; exit 1 ;;
+    esac
+}
+
 entries=($(nb list interstitial_journal/ | grep --color=never -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}' | sort -r))
 
 #make index.html
@@ -104,12 +126,12 @@ entries=($(nb list interstitial_journal/ | grep --color=never -oE '[0-9]{4}-[0-9
     #div "$(paragraph "Entries:" "$(ul "$(for entry in "${entries[@]}"; do list_item "$(href "$entry")"; done)")")"
 
     for entry in "${entries[@]}"; do
-        TODAY="$entry"
+        TODAY="${entry}"
         #if ! [[ -a "$OUTPUT_DIR" ]];then mkdir "$OUTPUT_DIR"; fi
-        title_figlet "$(date -d "$TODAY" -R | awk '{print $1, $2, $3, $4}')"
+        title_figlet "$(parse_date "${TODAY}" -R | awk '{print $1, $2, $3, $4}')"
         moon_phase_html
         href "$entry"
-        paragraph "$(nb export pandoc interstitial_journal/$entry --from markdown --to html)"
+        paragraph "$(nb export pandoc interstitial_journal/${entry}.md --from markdown --to html)"
     done
 
     kilroysay "Kilroy was here"
@@ -118,13 +140,13 @@ entries=($(nb list interstitial_journal/ | grep --color=never -oE '[0-9]{4}-[0-9
 
 # make journal entry pages
 for entry in "${entries[@]}"; do
-    TODAY="$entry"
+    TODAY="${entry}"
     if ! [[ -a "$OUTPUT_DIR" ]];then mkdir "$OUTPUT_DIR"; fi
     (
         header
-        title_figlet "$(date -d "$TODAY" -R | awk '{print $1, $2, $3, $4}')"
+        title_figlet "$(parse_date "${TODAY}" -R | awk '{print $1, $2, $3, $4}')"
         moon_phase_html
-        paragraph "$(nb export pandoc interstitial_journal/$entry --from markdown --to html)"
+        paragraph "$(nb export pandoc interstitial_journal/${entry}.md --from markdown --to html)"
         footer
     ) > "${OUTPUT_DIR}/${entry}.html"
 done
